/**
 * Parses Obsidian-compatible YAML frontmatter from a Markdown file.
 * Handles the human-readable YAML subset generated by this app's vault exporter,
 * including simple scalars, quoted strings, and list items.
 *
 * Returns `{ meta, body }` where body is the text after the closing `---`.
 */
export function parseFrontmatter(text: string): { meta: Record<string, unknown>; body: string } {
	const match = text.match(/^---\n([\s\S]*?)\n---\n?\n?([\s\S]*)$/);
	if (!match) return { meta: {}, body: text };
	return { meta: parseYamlBlock(match[1]), body: match[2] };
}

function parseYamlBlock(yaml: string): Record<string, unknown> {
	const meta: Record<string, unknown> = {};
	const lines = yaml.split('\n');
	let i = 0;

	while (i < lines.length) {
		const line = lines[i];
		if (!line.trim() || line.startsWith('  ')) {
			i++;
			continue;
		}

		const colonIdx = line.indexOf(':');
		if (colonIdx === -1) {
			i++;
			continue;
		}

		const key = line.slice(0, colonIdx).trim();
		const rawVal = line.slice(colonIdx + 1).trimStart();

		if (rawVal === '' || rawVal === undefined) {
			// Possibly followed by array items on the next lines
			const items: unknown[] = [];
			i++;
			while (i < lines.length && lines[i].startsWith('  - ')) {
				items.push(parseScalar(lines[i].slice(4)));
				i++;
			}
			meta[key] = items;
		} else if (rawVal === '[]') {
			meta[key] = [];
			i++;
		} else if (rawVal.startsWith('[') && rawVal.endsWith(']')) {
			// Inline array: [val1, val2, val3]
			const inner = rawVal.slice(1, -1).trim();
			meta[key] = inner
				? inner.split(',').map((s) => parseScalar(s.trim()))
				: [];
			i++;
		} else {
			meta[key] = parseScalar(rawVal);
			i++;
		}
	}

	return meta;
}

function parseScalar(s: string): unknown {
	const t = s.trim();
	if (t === 'null' || t === '~') return null;
	if (t === 'true') return true;
	if (t === 'false') return false;
	if (/^-?\d+$/.test(t)) return Number(t);
	if (/^-?\d+\.\d+$/.test(t)) return Number(t);
	// Unquote double-quoted strings
	if (t.startsWith('"') && t.endsWith('"')) {
		return t.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\');
	}
	return t;
}

/**
 * Extracts the text content of a named `## Heading` section from a Markdown body.
 * Returns an empty string if the section is not found.
 */
export function extractSection(body: string, heading: string): string {
	const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	const regex = new RegExp(`##\\s+${escaped}\\s*\\n([\\s\\S]*?)(?=\\n##\\s|$)`, 'i');
	const m = body.match(regex);
	if (!m) return '';
	const content = m[1].trim();
	// Strip placeholder text set during export
	if (content === '_No writing objectives set._' || content === '_No content yet._') return '';
	return content;
}
